name: Docker Image CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: unchartedsky/macgyver/macgyver
        registry: docker.pkg.github.com
        dockerfile: Dockerfile
        buildoptions: "--compress --force-rm"
        tag_names: true
        username: ${{ secrets.GITHUB_TOKEN }}
        password: ${{ github.actor }}
